pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
  stages {
        stage('Docker Login') {
            steps {
                // Add --password-stdin to run docker login command non-interactively
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage ('k8s credentials'){
          steps{
            kubernetesDeploy configs: '', kubeConfig: [path: ' ansible-playbook k8s/k8s-playbook.yml'], kubeconfigId: 'kubernetes', secretName: '', ssh: [sshCredentialsId: '*', sshServer: ''], textCredentials: [certificateAuthorityData: '', clientCertificateData: '', clientKeyData: '', serverUrl: 'https://']
          }
        }
        stage('deployment k8s') {
            steps {
                  sh """
                ansible-playbook k8s/k8s-playbook.yml
                """
            }
        }
  }
}