pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
  stages {
        stage('Docker Login') {
            steps {
                // Add --password-stdin to run docker login command non-interactively
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        // stage ('k8s credentials'){
        //   steps{
        //       script{
        //             kubernetesDeploy (configs: 'k8s/secret.yml',kubeconfigId: 'kubernetes')
        //         }
        //   }
        // }
        stage('deployment k8s') {
            steps {
              kubernetesDeploy (configs: 'k8s/k8s-playbook.yml',kubeconfigId: 'kubernetes',)
              // ansible-playbook k8s/k8s-playbook.yml
                //   sh """
                // ansible-playbook k8s/k8s-playbook.yml
                // """
            }
        }
  }
}