---
- name : "k8s auto build"
  hosts: localhost
  tasks:  
   - name: delete namespace ninja
     command: kubectl delete ns ninja
     ignore_errors: yes
    

   - name: create ns ninja
     command: kubectl create ns ninja

   - name: deploy secret
     command: kubectl apply -f secret.yml

   - name: deploy mongo.yml
     command: kubectl apply -f mongo.yml

   - name: deploy configmap
     command: kubectl apply -f configMap.yml

   - name: deploy mongo-express
     command: kubectl apply -f mongo-express.yml
  
   - name: deploy nodejsApp
     command: kubectl apply -f nodejs.yml

   - name: show all deployments
     command: kubectl get all -n ninja